name: Frontend setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version-file: .nvmrc
        cache: npm
    - run: npm ci
