name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install packages
        run: npm clean-install

      - name: Build site & styles
        run: npm run build && npm run build:sass

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install packages
        run: npm clean-install

      - name: Check formatting
        run: npm run prettier

  lint:
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install packages
        run: npm clean-install

      - name: Check formatting
        run: npm run lint
