name: CI
on: [push]
jobs:
  stylelint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i

      - name: Run linting tests
        run: npm run lint

      - name: Run formatting tests
        run: npm run prettier
